In [13]:
import torch
import torch.nn as nn
import math


# --------------------------------
# 1. Input embeddings
# --------------------------------

x = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],   # I
    [0.0, 1.0, 0.0, 1.0],   # love
    [1.0, 1.0, 0.0, 0.0]    # dogs
])


# --------------------------------
# 2. Create Q, K, V projections
# --------------------------------

W_q = nn.Linear(4, 4, bias=False)
W_k = nn.Linear(4, 4, bias=False)
W_v = nn.Linear(4, 4, bias=False)


# --------------------------------
# 3. Generate Q, K, V
# --------------------------------

Q = W_q(x)
K = W_k(x)
V = W_v(x)


print("Q:")
print(Q)

print("\nK:")
print(K)

print("\nV:")
print(V)


# --------------------------------
# 4. Calculate attention scores
# --------------------------------

scores = Q @ K.T

print("\nRaw Attention Scores:")
print(scores)


# --------------------------------
# 5. Scale scores
# --------------------------------

d_k = K.size(-1)

scores = scores / math.sqrt(d_k)

print("\nScaled Attention Scores:")
print(scores)


# --------------------------------
# 6. Softmax
# --------------------------------

attention_weights = torch.softmax(
    scores,
    dim=-1
)

print("\nAttention Weights:")
print(attention_weights)


# --------------------------------
# 7. Weighted sum of Values
# --------------------------------

output = attention_weights @ V

print("\nAttention Output:")
print(output)

Q:
tensor([[ 0.3564, -0.0550,  0.6621, -0.5474],
        [-0.3707,  0.5325, -0.1311, -0.8401],
        [-0.0959,  0.2811,  0.4709, -0.6777]], grad_fn=<MmBackward0>)

K:
tensor([[ 0.7754, -0.0180, -0.1409,  0.2972],
        [ 0.4376,  0.5526, -0.0647,  0.0790],
        [ 0.4014,  0.1551,  0.5443,  0.5317]], grad_fn=<MmBackward0>)

V:
tensor([[ 0.0599,  0.4819,  0.1007,  0.1463],
        [ 0.4837, -0.5376, -0.3937, -0.0471],
        [ 0.4778, -0.1598, -0.5305,  0.1182]], grad_fn=<MmBackward0>)

Raw Attention Scores:
tensor([[ 0.0214,  0.0395,  0.2038],
        [-0.5283,  0.0741, -0.5843],
        [-0.3472,  0.0293, -0.0990]], grad_fn=<MmBackward0>)

Scaled Attention Scores:
tensor([[ 0.0107,  0.0197,  0.1019],
        [-0.2641,  0.0370, -0.2922],
        [-0.1736,  0.0146, -0.0495]], grad_fn=<DivBackward0>)

Attention Weights:
tensor([[0.3221, 0.3250, 0.3529],
        [0.3009, 0.4066, 0.2925],
        [0.2995, 0.3615, 0.3390]], grad_fn=<SoftmaxBackward0>)

Attention Output:
tensor([[ 0.3

# Attention(Q,K,V)=softmax(QK^T/root(dk)​)V