Goal:
# Predict the median house price using house information.

 We have completed:
 1. Import Libraries
 2. Load Dataset
 3. Explore Dataset
 4. Separate Features and Target
 5. Train-Test Split
 6. Feature Scaling
 7. Convert to PyTorch Tensors

# **Importing the** **Libraries**

In [ ]:
import torch
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# **Load the Dataset**

In [ ]:
housing = fetch_california_housing()

print("=" * 60)
print("Keys inside the dataset")
print("=" * 60)
print(housing.keys())

Keys inside the dataset
dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])


# **Convert The Code Pandas Dataframe**

In [ ]:
df = pd.DataFrame(
    housing.data,
    columns=housing.feature_names
)

# Add the target column
df["Price"] = housing.target

# **Explore the Dataset**

In [ ]:
print("\n" + "=" * 60)
print("First 5 Rows")
print("=" * 60)
print(df.head())

print("\n" + "=" * 60)
print("Dataset Shape")
print("=" * 60)
print(df.shape)

print("\n" + "=" * 60)
print("Column Names")
print("=" * 60)
print(df.columns)

print("\n" + "=" * 60)
print("Data Types")
print("=" * 60)
print(df.dtypes)

print("\n" + "=" * 60)
print("Missing Values")
print("=" * 60)
print(df.isnull().sum())

print("\n" + "=" * 60)
print("Statistics")
print("=" * 60)
print(df.describe())


First 5 Rows
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422  

Dataset Shape
(20640, 9)

Column Names
Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'Price'],
      dtype='object')

Data Types
MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
Price         float64
dty

# **Split X and Y**

In [ ]:
X = df.drop("Price", axis=1)

y = df["Price"]

print("\n" + "=" * 60)
print("Features Shape")
print("=" * 60)
print(X.shape)

print("\n" + "=" * 60)
print("Target Shape")
print("=" * 60)
print(y.shape)


Features Shape
(20640, 8)

Target Shape
(20640,)


# **Tranin & Test Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\n" + "=" * 60)
print("After Train-Test Split")
print("=" * 60)

print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)


After Train-Test Split
X_train : (16512, 8)
X_test  : (4128, 8)
y_train : (16512,)
y_test  : (4128,)


# **Feature Scaling**

In [ ]:
scaler = StandardScaler()

# Learn mean & std from training data
# Then scale training data
X_train = scaler.fit_transform(X_train)

# Use SAME mean & std on testing data
X_test = scaler.transform(X_test)

print("\n" + "=" * 60)
print("After Scaling")
print("=" * 60)

print("First 5 Scaled Samples")
print(X_train[:5])

print("\nMean of each feature (approximately 0)")
print(X_train.mean(axis=0))

print("\nStd of each feature (approximately 1)")
print(X_train.std(axis=0))


After Scaling
First 5 Scaled Samples
[[-0.326196    0.34849025 -0.17491646 -0.20836543  0.76827628  0.05137609
  -1.3728112   1.27258656]
 [-0.03584338  1.61811813 -0.40283542 -0.12853018 -0.09890135 -0.11736222
  -0.87669601  0.70916212]
 [ 0.14470145 -1.95271028  0.08821601 -0.25753771 -0.44981806 -0.03227969
  -0.46014647 -0.44760309]
 [-1.01786438  0.58654547 -0.60001532 -0.14515634 -0.00743434  0.07750687
  -1.38217186  1.23269811]
 [-0.17148831  1.14200767  0.3490073   0.08662432 -0.48587717 -0.06883176
   0.5320839  -0.10855122]]

Mean of each feature (approximately 0)
[-6.51933288e-17 -9.25185854e-18 -1.98108110e-16 -1.70729064e-16
 -2.15159501e-19  4.93656580e-17  6.40099515e-17  1.75333477e-15]

Std of each feature (approximately 1)
[1. 1. 1. 1. 1. 1. 1. 1.]


# **Converting Numpy Arrays to Pytorch Tensors**

In [ ]:
X_train = torch.tensor(
    X_train,
    dtype=torch.float32
)

X_test = torch.tensor(
    X_test,
    dtype=torch.float32)

y_train = torch.tensor(
    y_train.values,
    dtype=torch.float32
).view(-1, 1)

y_test = torch.tensor(
    y_test.values,
    dtype=torch.float32
).view(-1, 1)


# **Verifying Everything**

In [ ]:
print("\n" + "=" * 60)
print("Final Tensor Shapes")
print("=" * 60)

print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

print("\n" + "=" * 60)
print("Tensor Data Types")
print("=" * 60)

print(type(X_train))
print(type(y_train))


Final Tensor Shapes
X_train : torch.Size([16512, 8])
X_test  : torch.Size([4128, 8])
y_train : torch.Size([16512, 1])
y_test  : torch.Size([4128, 1])

Tensor Data Types
<class 'torch.Tensor'>
<class 'torch.Tensor'>


# **Model Building**

In [ ]:
import torch.nn as nn

class HousePriceModel(nn.Module):
  def __init__(self):
    super().__init__()
    # Define the Linear Layer
    #
    # nn.Linear(in_features, out_features)
    #
    # in_features  = 8
    # out_features = 1
    #
    # Internally PyTorch creates:
    #
    # Weight -> Shape (1, 8)
    # Bias   -> Shape (1)

    self.linear = nn.Linear(8, 1)

    # forward()
    #
    # This defines how the data flows through the network.
    #
    # Whenever we write:
    #
    # prediction = model(X_train)
    #
    # PyTorch automatically calls:
    #
    # prediction = model.forward(X_train)
    #
    # --------------------------------------------------------

  def forward(self, x):
    output = self.linear(x)
    return output

# **Create Model, Loss Function & Print Model**

In [ ]:
model = HousePriceModel()
criterion = nn.MSELoss()

print("=" * 60)
print("MODEL")
print("=" * 60)

print(model)

# ============================================================
# VIEW THE INITIAL WEIGHTS
# ============================================================

print("\n" + "=" * 60)
print("INITIAL WEIGHTS")
print("=" * 60)

print(model.linear.weight)

# Shape:
# (1, 8)
#
# One weight for each input feature.

# ============================================================
# VIEW THE INITIAL BIAS
# ============================================================

print("\n" + "=" * 60)
print("INITIAL BIAS")
print("=" * 60)

print(model.linear.bias)

MODEL
HousePriceModel(
  (linear): Linear(in_features=8, out_features=1, bias=True)
)

INITIAL WEIGHTS
Parameter containing:
tensor([[ 0.2739,  0.0750, -0.1543,  0.1822, -0.2664, -0.1359, -0.0639,  0.3345]],
       requires_grad=True)

INITIAL BIAS
Parameter containing:
tensor([0.0392], requires_grad=True)


# **Test the Model with Small Batch**

In [ ]:
sample = X_train[:5]

print("\n" + "=" * 60)
print("INPUT SHAPE")
print("=" * 60)

print(sample.shape)

# Pass through the model
prediction = model(sample)

print("\n" + "=" * 60)
print("OUTPUT SHAPE")
print("=" * 60)

print(prediction.shape)

print("\nPredictions:")
print(prediction)



INPUT SHAPE
torch.Size([5, 8])

OUTPUT SHAPE
torch.Size([5, 1])

Predictions:
tensor([[ 0.2667],
        [ 0.5251],
        [-0.1243],
        [ 0.3626],
        [ 0.1083]], grad_fn=<AddmmBackward0>)


# **Optimizer**

In [ ]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

# **Training Loop**

In [18]:
epochs = 1000

for epoch in range(epochs):

  prediction = model(X_train)

  loss = criterion(prediction, y_train)

  loss.backward()

  optimizer.step()

  optimizer.zero_grad()

  if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}] Loss: {loss.item():.4f}")

Epoch [100/1000] Loss: 0.7128
Epoch [200/1000] Loss: 0.5995
Epoch [300/1000] Loss: 0.5778
Epoch [400/1000] Loss: 0.5631
Epoch [500/1000] Loss: 0.5522
Epoch [600/1000] Loss: 0.5440
Epoch [700/1000] Loss: 0.5379
Epoch [800/1000] Loss: 0.5333
Epoch [900/1000] Loss: 0.5299
Epoch [1000/1000] Loss: 0.5272


# **Model Evaluation**

In [19]:
model.eval()

with torch.no_grad():
  test_prediction = model(X_test)

  test_loss = criterion(test_prediction, y_test)

print(f"Test Loss : {test_loss.item():.4f}")

Test Loss : 0.5613
